---
name: URI-ToABS
version: v0.0.2
author:
  - 'Tsutomu KOYACHI <rtk2106@gmail.com>'
abstract: 'convert url has relative paths("..", ".") to absolute path.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  URI::ToABS:
    file: lib/URI/ToABS.pm
    version: v0.0.2
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
